name: Build Wheel

on: workflow_dispatch

jobs:
  build-src:
    name: Build source dist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - name: Install requirements
        run: pip install setuptools
      
      - name: Build source package
        run: python setup.py sdist
  
      - name: Upload source package
        uses: actions/upload-artifact@v4
        with:
          name: source-dist
          path: ./dist/*.tar.gz

  build-wheel:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]

    steps:
      - uses: actions/checkout@v4
 
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: cp310-* cp311-* cp312-* cp313-*

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
