name: Publish to Pypi
on: workflow_dispatch
jobs:  
  publish-to-testpypi:
    name: Publish Python distribution to PyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://pypi.org/p/larch-reactive

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Get release
      id: get_release
      uses: thebritican/fetch-latest-release@v2.0.0
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: create dist
      run: |
       mkdir dist
    
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: tags/${{ steps.get_release.outputs.tag_name }}
        file: '.*[.](whl|tar.gz|zip)$'
        regex: true
        target: "dist/"

    - name: Debug
      run: |
       pwd
       ls dist
       echo "------------------"

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        skip-existing: true
